service: postrealm-api
provider:
  memorySize: 1500
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: Allow
      Action:
            - 'sns:Publish'
            - 'sns:CreateTopic'
      Resource : '*'
    - Effect: Allow
      Action:
            - 'ses:*'
      Resource : '*'  
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "*"
    - Effect : Allow
      Action:
        - "secretsmanager:*"
      Resource:
        - "*"
        

package:
  exclude:
    - ./**
  include:
    - ./build/**
functions:
  api:
    timeout: 30
    handler: build/api
    events:
      - http:
          path: /
          method: any
          cors: true # <-- CORS!
      - http:
          path: "/{proxy+}"
          method: any
          cors: true # <-- CORS!


