version: "3.3"
    
services:
  db:
    ports:
      - 3320:3306
    image: mysql:5.7
    volumes:
      - ~/.rpost-it-db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpost-it
      MYSQL_USER: some
      MYSQL_PASSWORD: dumb
    