version: "3.9"
    
services:
  db:
    ports:
      - 3306:3306
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpost-it
      MYSQL_USER: some
      MYSQL_PASSWORD: dumb
    